# Generated by Django 5.1.5 on 2025-01-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_income', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('loss_tolerance', models.CharField(blank=True, max_length=50, null=True)),
                ('market_reaction', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_assets', models.JSONField(blank=True, null=True)),
                ('investment_experience', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'users',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
