# Generated by Django 4.2.18 on 2025-02-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favoritestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
