# Generated by Django 4.2.18 on 2025-02-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_investment'),
        ('users', '0003_remove_user_is_superuser'),
    ]

    operations = [
    ]
