# Generated by Django 4.2.18 on 2025-02-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0003_investment_0003_remove_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='investment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
