# Generated by Django 4.2.18 on 2025-02-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_investment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='investment',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
