# Generated by Django 4.2.19 on 2025-02-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_investment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_sectors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
